# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rails secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 4ee7927a1217ddf32122d0f6776ea4e72f46d3c132ee060c83f199df863292fde3e999f6d0a1d1b5d3000bf859316453950747b96b1a6d9f321e7d3753dbd675

test:
  secret_key_base: 81fc8bc350fc47e002d4ff73fb14ba9501d01f6d9870b6b5ca882815f5eb0bfd5b01a2e8d5018a55f0d2273a36ba4c3f650d70cf716aaa6662516c39a78e119d

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
